//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseApplication.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuna
    {
        public Comuna()
        {
            this.Examinador = new HashSet<Examinador>();
        }
    
        public int Id { get; set; }
        public string ComunaDescription { get; set; }
        public int RegionId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Examinador> Examinador { get; set; }
    }
}
