//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseApplication.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminadorRol
    {
        public int Id { get; set; }
        public int ExaminadorId { get; set; }
        public int RolId { get; set; }
    
        public virtual Examinador Examinador { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
