//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseApplication.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.ExaminadorRol = new HashSet<ExaminadorRol>();
        }
    
        public int Id { get; set; }
        public string RolDescription { get; set; }
    
        public virtual ICollection<ExaminadorRol> ExaminadorRol { get; set; }
    }
}
